### ISSUE TITLE
Ascii error

### ISSUE THREAD

**Issue by flicfloc** [phdesign/flickr-rsync#2]
Hi eXperts,

in some cases you get this error :

Traceback (most recent call last):
  File "/usr/local/bin/flickr-rsync", line 9, in <module>
    load_entry_point('flickr-rsync==1.0.4', 'console_scripts', 'flickr-rsync')()
  File "build/bdist.linux-i686/egg/flickr_rsync/__init__.py", line 51, in main
  File "build/bdist.linux-i686/egg/flickr_rsync/sync.py", line 29, in run
  File "build/bdist.linux-i686/egg/flickr_rsync/sync.py", line 49, in _merge_folders
  File "build/bdist.linux-i686/egg/flickr_rsync/flickr_storage.py", line 73, in list_files
  File "build/bdist.linux-i686/egg/flickr_rsync/flickr_storage.py", line 143, in _get_file_info
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)

Do you need some other data ? Logs ? anything else ?

thanks for the great work!
:)

Fred

**Comment by hefistion** [comment]
same mistake, when a picture has a character with a tilde

Thank you
